import { randomUUID } from "node:crypto";
import webpush from "web-push";
import type { Db } from "./db.js";
import type { Mailer } from "./mailer.js";

/**
 * Getting a message to a colleague who is not looking at the app.
 *
 * This is the thing the spreadsheet could never do, and the reason it died: it
 * sat in a folder waiting to be opened, and nobody opened it. A carpool where a
 * driver does not learn that somebody asked for a seat until they happen to
 * check is the same failure wearing a nicer interface.
 *
 * Two channels, tried in order:
 *
 *   **Web push** — a real notification on the phone, delivered by the browser
 *   vendor's push service. No third party of ours is involved: the VAPID keys
 *   are generated by this server and the payload is encrypted to the
 *   subscription, so the push service relays bytes it cannot read.
 *
 *   **Email** — slower and less immediate, but it arrives on every device
 *   without permission prompts, and a colleague who has not enabled push still
 *   finds out.
 *
 * Both are attempted, because they fail in different ways: push is silent if
 * permission was revoked, and email lands in a folder nobody watches. Together
 * they are much more likely to reach somebody than either alone.
 */

export interface OutgoingNotification {
  /** Derived from the subject, never the send time, so retries do not re-buzz. */
  readonly id: string;
  readonly userId: string;
  readonly kind: string;
  readonly title: string;
  readonly body: string;
  /** Where tapping the notification should take them. */
  readonly path?: string;
}

export interface PushKeys {
  readonly publicKey: string;
  readonly privateKey: string;
  readonly subject: string;
}

export class Notifier {
  private readonly pushEnabled: boolean;

  constructor(
    private readonly db: Db,
    private readonly mailer: Mailer,
    keys: PushKeys | undefined,
    private readonly appUrl: string,
  ) {
    this.pushEnabled = Boolean(keys);
    if (keys) {
      webpush.setVapidDetails(keys.subject, keys.publicKey, keys.privateKey);
    }
  }

  get canPush(): boolean {
    return this.pushEnabled;
  }

  subscribe(userId: string, sub: { endpoint: string; keys: { p256dh: string; auth: string } }): void {
    this.db.run(
      `INSERT INTO push_subscriptions (id, userId, endpoint, p256dh, auth, createdAt)
       VALUES (?, ?, ?, ?, ?, ?)
       ON CONFLICT(endpoint) DO UPDATE SET userId = excluded.userId`,
      randomUUID(),
      userId,
      sub.endpoint,
      sub.keys.p256dh,
      sub.keys.auth,
      new Date().toISOString(),
    );
  }

  /**
   * Deliver, once.
   *
   * Returns false when this notification has already been sent. That check is
   * on the notification's own id rather than a timestamp, so a restarted
   * scheduler re-deriving the same reminder is a no-op instead of a second
   * buzz at six in the morning.
   */
  async send(n: OutgoingNotification): Promise<boolean> {
    const already = this.db.get<{ id: string }>(
      "SELECT id FROM sent_notifications WHERE id = ?",
      n.id,
    );
    if (already) return false;

    this.db.run(
      "INSERT INTO sent_notifications (id, userId, kind, at) VALUES (?, ?, ?, ?)",
      n.id,
      n.userId,
      n.kind,
      new Date().toISOString(),
    );

    await Promise.all([this.push(n), this.email(n)]);
    return true;
  }

  private async push(n: OutgoingNotification): Promise<void> {
    if (!this.pushEnabled) return;
    const subs = this.db.all<{ id: string; endpoint: string; p256dh: string; auth: string }>(
      "SELECT id, endpoint, p256dh, auth FROM push_subscriptions WHERE userId = ?",
      n.userId,
    );

    await Promise.all(
      subs.map(async (s) => {
        try {
          await webpush.sendNotification(
            { endpoint: s.endpoint, keys: { p256dh: s.p256dh, auth: s.auth } },
            JSON.stringify({ title: n.title, body: n.body, path: n.path ?? "/" }),
          );
        } catch (e) {
          const status = (e as { statusCode?: number }).statusCode;
          // 404/410 mean the browser has thrown the subscription away — the
          // colleague uninstalled, cleared data, or revoked permission. Keeping
          // it would mean retrying a dead endpoint forever.
          if (status === 404 || status === 410) {
            this.db.run("DELETE FROM push_subscriptions WHERE id = ?", s.id);
          } else {
            console.error("push failed:", status ?? e);
          }
        }
      }),
    );
  }

  private async email(n: OutgoingNotification): Promise<void> {
    if (!this.mailer.enabled) return;
    const user = this.db.get<{ email: string }>(
      "SELECT email FROM users WHERE id = ?",
      n.userId,
    );
    // Invite-mode rows carry a placeholder rather than a real address.
    if (!user?.email || user.email.startsWith("invite:")) return;

    await this.mailer.send(
      user.email,
      n.title,
      [n.body, "", `Open Ekpothe: ${this.appUrl}${n.path ?? "/"}`, "", "— Ekpothe"].join("\n"),
    );
  }
}

/** The notifications the pilot actually sends. Ids are derived from the subject. */
export const notifications = {
  seatRequested: (
    driverId: string,
    bookingId: string,
    riderName: string,
    boardZone: string,
    time: string,
  ): OutgoingNotification => ({
    id: `seat-requested:${bookingId}`,
    userId: driverId,
    kind: "seat_requested",
    title: `${riderName} wants a seat`,
    body: `Boarding at ${boardZone}, ${time}. Open Ekpothe to accept or decline.`,
    path: "/",
  }),

  seatAccepted: (
    riderId: string,
    bookingId: string,
    driverName: string,
    time: string,
  ): OutgoingNotification => ({
    id: `seat-accepted:${bookingId}`,
    userId: riderId,
    kind: "seat_accepted",
    title: `${driverName} accepted your seat`,
    body: `You're riding together at ${time}. Their contact details are now in the app.`,
    path: "/",
  }),

  /**
   * Declining is never attributed.
   *
   * The rider is told the seat is unavailable, not who declined or why. In an
   * office of this size an attributed decline is a lasting social cost, and the
   * fear of it would stop people asking at all.
   */
  seatDeclined: (riderId: string, bookingId: string, time: string): OutgoingNotification => ({
    id: `seat-declined:${bookingId}`,
    userId: riderId,
    kind: "seat_declined",
    title: "That seat is no longer available",
    body: `The ${time} seat didn't work out. Try another ride, or ask to be alerted.`,
    path: "/",
  }),

  /** T−45min, both sides. The main defence against no-shows. */
  reconfirm: (
    userId: string,
    rideId: string,
    counterpartName: string,
    time: string,
  ): OutgoingNotification => ({
    id: `reconfirm:${rideId}:${userId}`,
    userId,
    kind: "reconfirm",
    title: `Still on for ${time}?`,
    body: `With ${counterpartName}. A quick check saves them waiting.`,
    path: "/",
  }),

  /**
   * A colleague has registered and is waiting.
   *
   * Sent to the administrator, because a queue nobody is told about is a queue
   * nobody empties — and a colleague who registers on Sunday and hears nothing
   * by Monday has already decided the app does not work.
   */
  registrationReceived: (
    adminId: string,
    pendingUserId: string,
    who: string,
  ): OutgoingNotification => ({
    id: `registration:${pendingUserId}`,
    userId: adminId,
    kind: "registration_received",
    title: `${who} wants to join Ekpothe`,
    body: "Open Ekpothe → Admin to approve or leave them waiting.",
    path: "/",
  }),

  /**
   * Approved. Sent by email in practice: they have never signed in, so there is
   * no push subscription to buzz yet. Their personal address is the only way to
   * reach them, and it is the reason one is asked for.
   */
  registrationApproved: (userId: string): OutgoingNotification => ({
    id: `approved:${userId}`,
    userId,
    kind: "registration_approved",
    title: "You're in — Ekpothe is open to you",
    body: "Sign in with the email and password you chose.",
    path: "/",
  }),

  newRideOnYourRoute: (
    riderId: string,
    rideId: string,
    driverName: string,
    route: string,
    time: string,
  ): OutgoingNotification => ({
    id: `new-ride:${rideId}:${riderId}`,
    userId: riderId,
    kind: "new_ride",
    title: `${driverName} is driving your route`,
    body: `${route}, ${time}. There's a seat if you want it.`,
    path: "/",
  }),
};
