/**
 * One-time setup: generate push keys and write a starter .env.local.
 *
 *   npm run setup
 *
 * VAPID keys are generated here rather than obtained from anyone: they are a
 * self-signed keypair that identifies *this server* to the browser vendors'
 * push services. Nobody issues them and nothing verifies them beyond the pair
 * matching, so there is no account to create and no third party involved.
 *
 * Existing values in .env.local are preserved — running this twice will not
 * rotate keys already in use, which would silently break every subscription
 * colleagues have already granted.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import webpush from "web-push";

const path = join(process.cwd(), ".env.local");
const existing = existsSync(path) ? readFileSync(path, "utf8") : "";

const has = (key) => new RegExp(`^${key}=.+`, "m").test(existing);

if (has("VAPID_PUBLIC_KEY") && has("VAPID_PRIVATE_KEY")) {
  console.log(".env.local already has VAPID keys — leaving them alone.");
  console.log("Rotating them would break every push subscription colleagues have granted.");
  process.exit(0);
}

const keys = webpush.generateVAPIDKeys();

const contents = `# Ekpothe — local configuration. NEVER commit this file.
#
# Generated by \`npm run setup\` on ${new Date().toISOString().slice(0, 10)}.

# --- Push notifications -----------------------------------------------------
# A self-signed keypair identifying this server to browser push services.
# No account, no third party. Rotating these breaks existing subscriptions.
VAPID_PUBLIC_KEY=${keys.publicKey}
VAPID_PRIVATE_KEY=${keys.privateKey}
VAPID_SUBJECT=mailto:you@example.com

# --- Email ------------------------------------------------------------------
# Fill these in from your mail provider. See docs/EMAIL_SETUP.md.
# Without them the app still pushes to phones; it just cannot send email.
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=Ekpothe <you@example.com>

# --- Access -----------------------------------------------------------------
BLOCKED_EMAIL_DOMAINS=giz.de
ADMIN_EMAIL=
APP_URL=http://localhost:8080

# --- Deployment -------------------------------------------------------------
# TRUST_PROXY=1        when something in front terminates TLS
# DB_PATH=/data/carpool.db
`;

writeFileSync(path, existing ? existing + "\n" + contents : contents, "utf8");

console.log("Wrote .env.local (git-ignored).\n");
console.log("VAPID public key  (safe to share, goes in the browser):");
console.log(`  ${keys.publicKey}\n`);
console.log("VAPID private key (secret — server only, never commit):");
console.log(`  ${keys.privateKey}\n`);
console.log("Next: fill in the SMTP_* values — see docs/EMAIL_SETUP.md");
